### ISSUE TITLE
To-do for Huawei device features

### ISSUE THREAD

**Issue by divadsn** [berkeley-pie/android_patcher#1]
Huawei devices have some device features which can be useful for a lot of us, therefore let's add support for those to our forked AOSP repos as patches.

Currently planned features:
- [ ] Display color modes (missing LiveDisplay)
- [x] Glove mode (high sensitivty touchmode)
- [x] Super Charge (tm) support
- [ ] Fingerprint gesture-based navigation

**Comment by divadsn** [comment]
Super Charge got implemented in https://github.com/divadsn/frameworks_base/commit/e839b1f6ba756f240d9eeaddcac88f0fbbc30c1d

Although I'm not sure if we might not check `/sys/class/power_supply/Battery/fcp_status` as well.

**Comment by divadsn** [comment]
Glove mode is only a matter of modifying a sys path after boot has completed:
`echo 1 > /sys/touchscreen/touch_glove`

Taken from https://github.com/AICP/device_huawei_kirin970-common/commit/d61c0c746c9e1c63188c9f54d698f495e615633f
